/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'adminOrganizationSettings', { get: function () { return require('./admin-organization-settings'); } });
Object.defineProperty(exports, 'agentPool', { get: function () { return require('./agent-pool'); } });
Object.defineProperty(exports, 'agentPoolAllowedWorkspaces', { get: function () { return require('./agent-pool-allowed-workspaces'); } });
Object.defineProperty(exports, 'agentToken', { get: function () { return require('./agent-token'); } });
Object.defineProperty(exports, 'noCodeModule', { get: function () { return require('./no-code-module'); } });
Object.defineProperty(exports, 'notificationConfiguration', { get: function () { return require('./notification-configuration'); } });
Object.defineProperty(exports, 'oauthClient', { get: function () { return require('./oauth-client'); } });
Object.defineProperty(exports, 'organization', { get: function () { return require('./organization'); } });
Object.defineProperty(exports, 'organizationMembership', { get: function () { return require('./organization-membership'); } });
Object.defineProperty(exports, 'organizationModuleSharing', { get: function () { return require('./organization-module-sharing'); } });
Object.defineProperty(exports, 'organizationRunTask', { get: function () { return require('./organization-run-task'); } });
Object.defineProperty(exports, 'organizationToken', { get: function () { return require('./organization-token'); } });
Object.defineProperty(exports, 'policy', { get: function () { return require('./policy'); } });
Object.defineProperty(exports, 'policySet', { get: function () { return require('./policy-set'); } });
Object.defineProperty(exports, 'policySetParameter', { get: function () { return require('./policy-set-parameter'); } });
Object.defineProperty(exports, 'project', { get: function () { return require('./project'); } });
Object.defineProperty(exports, 'projectPolicySet', { get: function () { return require('./project-policy-set'); } });
Object.defineProperty(exports, 'projectVariableSet', { get: function () { return require('./project-variable-set'); } });
Object.defineProperty(exports, 'registryModule', { get: function () { return require('./registry-module'); } });
Object.defineProperty(exports, 'runTrigger', { get: function () { return require('./run-trigger'); } });
Object.defineProperty(exports, 'samlSettings', { get: function () { return require('./saml-settings'); } });
Object.defineProperty(exports, 'sentinelPolicy', { get: function () { return require('./sentinel-policy'); } });
Object.defineProperty(exports, 'sshKey', { get: function () { return require('./ssh-key'); } });
Object.defineProperty(exports, 'team', { get: function () { return require('./team'); } });
Object.defineProperty(exports, 'teamAccess', { get: function () { return require('./team-access'); } });
Object.defineProperty(exports, 'teamMember', { get: function () { return require('./team-member'); } });
Object.defineProperty(exports, 'teamMembers', { get: function () { return require('./team-members'); } });
Object.defineProperty(exports, 'teamOrganizationMember', { get: function () { return require('./team-organization-member'); } });
Object.defineProperty(exports, 'teamOrganizationMembers', { get: function () { return require('./team-organization-members'); } });
Object.defineProperty(exports, 'teamProjectAccess', { get: function () { return require('./team-project-access'); } });
Object.defineProperty(exports, 'teamToken', { get: function () { return require('./team-token'); } });
Object.defineProperty(exports, 'terraformVersion', { get: function () { return require('./terraform-version'); } });
Object.defineProperty(exports, 'variable', { get: function () { return require('./variable'); } });
Object.defineProperty(exports, 'variableSet', { get: function () { return require('./variable-set'); } });
Object.defineProperty(exports, 'workspace', { get: function () { return require('./workspace'); } });
Object.defineProperty(exports, 'workspacePolicySet', { get: function () { return require('./workspace-policy-set'); } });
Object.defineProperty(exports, 'workspaceRun', { get: function () { return require('./workspace-run'); } });
Object.defineProperty(exports, 'workspaceRunTask', { get: function () { return require('./workspace-run-task'); } });
Object.defineProperty(exports, 'workspaceVariableSet', { get: function () { return require('./workspace-variable-set'); } });
Object.defineProperty(exports, 'dataTfeAgentPool', { get: function () { return require('./data-tfe-agent-pool'); } });
Object.defineProperty(exports, 'dataTfeGithubAppInstallation', { get: function () { return require('./data-tfe-github-app-installation'); } });
Object.defineProperty(exports, 'dataTfeIpRanges', { get: function () { return require('./data-tfe-ip-ranges'); } });
Object.defineProperty(exports, 'dataTfeOauthClient', { get: function () { return require('./data-tfe-oauth-client'); } });
Object.defineProperty(exports, 'dataTfeOrganization', { get: function () { return require('./data-tfe-organization'); } });
Object.defineProperty(exports, 'dataTfeOrganizationMembers', { get: function () { return require('./data-tfe-organization-members'); } });
Object.defineProperty(exports, 'dataTfeOrganizationMembership', { get: function () { return require('./data-tfe-organization-membership'); } });
Object.defineProperty(exports, 'dataTfeOrganizationRunTask', { get: function () { return require('./data-tfe-organization-run-task'); } });
Object.defineProperty(exports, 'dataTfeOrganizationTags', { get: function () { return require('./data-tfe-organization-tags'); } });
Object.defineProperty(exports, 'dataTfeOrganizations', { get: function () { return require('./data-tfe-organizations'); } });
Object.defineProperty(exports, 'dataTfeOutputs', { get: function () { return require('./data-tfe-outputs'); } });
Object.defineProperty(exports, 'dataTfePolicySet', { get: function () { return require('./data-tfe-policy-set'); } });
Object.defineProperty(exports, 'dataTfeProject', { get: function () { return require('./data-tfe-project'); } });
Object.defineProperty(exports, 'dataTfeSamlSettings', { get: function () { return require('./data-tfe-saml-settings'); } });
Object.defineProperty(exports, 'dataTfeSlug', { get: function () { return require('./data-tfe-slug'); } });
Object.defineProperty(exports, 'dataTfeSshKey', { get: function () { return require('./data-tfe-ssh-key'); } });
Object.defineProperty(exports, 'dataTfeTeam', { get: function () { return require('./data-tfe-team'); } });
Object.defineProperty(exports, 'dataTfeTeamAccess', { get: function () { return require('./data-tfe-team-access'); } });
Object.defineProperty(exports, 'dataTfeTeamProjectAccess', { get: function () { return require('./data-tfe-team-project-access'); } });
Object.defineProperty(exports, 'dataTfeVariableSet', { get: function () { return require('./data-tfe-variable-set'); } });
Object.defineProperty(exports, 'dataTfeVariables', { get: function () { return require('./data-tfe-variables'); } });
Object.defineProperty(exports, 'dataTfeWorkspace', { get: function () { return require('./data-tfe-workspace'); } });
Object.defineProperty(exports, 'dataTfeWorkspaceIds', { get: function () { return require('./data-tfe-workspace-ids'); } });
Object.defineProperty(exports, 'dataTfeWorkspaceRunTask', { get: function () { return require('./data-tfe-workspace-run-task'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

